version: 2
updates:
- package-ecosystem: npm
  directory: "/src/blog"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - jvandertil

- package-ecosystem: nuget
  directory: "/src/blog-comment-function"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - jvandertil

- package-ecosystem: nuget
  directory: "/eng/_pipeline"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - jvandertil