version: 2
updates:
- package-ecosystem: npm
  directory: "/src/blog"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - jvandertil
- package-ecosystem: nuget
  directory: "/src/Uploader"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - jvandertil
