trigger:
  branches:
    include:
      - 'main'
      - 'master'

variables:
  NUKE_TELEMETRY_OPTOUT: 1

  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1
  DOTNET_GENERATE_ASPNET_CERTIFICATE: 0

  IS_PULLREQUEST: $[ eq(variables['Build.Reason'], 'PullRequest') ]
  IS_MAIN_BRANCH: $[ eq(variables['Build.SourceBranch'], 'refs/heads/master') ]

stages:
- stage: Build
  jobs:
  - job: Build
    steps: 
      - task: UseDotNet@2
        displayName: Ensure latest .NET SDK available
        inputs:
          packageType: 'sdk'
          version: '6.x'
      - pwsh: |
          .\build.ps1 --target Clean Build
        displayName: Execute Nuke build

      - task: PublishTestResults@2
        condition: always()
        displayName: Publish Test Results
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '$(Build.SourcesDirectory)/artifacts/TestResults/*.trx'
          mergeTestResults: true

      - pwsh: |
          cd artifacts
          mkdir drop
          copy *.zip drop
        displayName: Prepare artifact drop

      - task: PublishPipelineArtifact@1
        displayName: Publish artifacts
        inputs:
          targetPath: './artifacts/drop'
          artifact: 'build'
          publishLocation: 'pipeline'

- stage: Deploy
  condition: |
    and(
      eq(variables['IS_MAIN_BRANCH'], true), 
      eq(variables['IS_PULLREQUEST'], false)
    )
  jobs:
  - deployment: Deploy
    environment: jvandertil-blog-prd
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - checkout: self

          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'build'
              targetPath: './artifacts'

          - task: UseDotNet@2
            displayName: Ensure latest .NET SDK available
            inputs:
              packageType: 'sdk'
              version: '6.x'
          - task: AzureCLI@2
            displayName: 'Run deployment script'
            inputs:
              azureSubscription: 'Azure jvandertil.nl prd'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                .\build.ps1 Deploy --environment prd --cloudflare-api-key $env:CLOUDFLARE_API_KEY --cloudflare-zone-id $env:CLOUDFLARE_ZONE_ID
            env:
              CLOUDFLARE_API_KEY: $(SECRET_CF_API_KEY)
              CLOUDFLARE_ZONE_ID: $(SECRET_CF_ZONE_ID)

