trigger:
  branches:
    include:
      - 'main'

variables:
  NUKE_TELEMETRY_OPTOUT: 1

  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1
  DOTNET_GENERATE_ASPNET_CERTIFICATE: 0

stages:
- stage: Build
  jobs:
  - job:
    steps: 
      - task: UseDotNet@2
        displayName: Ensure latest .NET SDK available
        inputs:
          packageType: 'sdk'
          version: '6.x'
      - pwsh: |
          .\build.ps1 --target Clean Build
        displayName: Execute Nuke build

      - task: PublishTestResults@2
        condition: always()
        displayName: Publish Test Results
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '$(Build.SourcesDirectory)\artifacts\TestResults\*.trx'
          mergeTestResults: true

      - pwsh: |
          cd artifacts
          mkdir drop
          copy *.zip drop
        displayName: Prepare artifact drop

      - task: PublishPipelineArtifact@1
        displayName: Publish artifacts
        inputs:
          targetPath: './artifacts/drop'
          artifact: 'build'
          publishLocation: 'pipeline'

- stage: Deploy
  jobs:
  - deployment:
    environment: jvandertil-blog-tst
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - checkout: self

          - download: current
            artifact: drop
            target: ./artifacts

          - task: UseDotNet@2
            displayName: Ensure latest .NET SDK available
            inputs:
              packageType: 'sdk'
              version: '6.x'
          - pwsh: |
              .\build.ps1 Deploy --environment tst --cloudflare-api-key $env:CLOUDFLARE_API_KEY --cloudflare-zone-id $env:CLOUDFLARE_ZONE_ID
            env:
              CLOUDFLARE_API_KEY: $(SECRET_CF_API_KEY)
              CLOUDFLARE_ZONE_ID: $(SECRET_CF_ZONE_ID)