languageCode = "en-us"
title = "Jos van der Til - Software Engineer"

# Highlighting should output classes
pygmentsUseClasses = true

[params]
	author = "Jos van der Til"
	authorBio = "Hi! I'm Jos, a Software Developer from the Netherlands."

	useSummaryIfNoDescription = true

	title = "Jos van der Til"
	subtitle = "Software Engineer"

	# Social media
	twitter = "josvandertil"
	github = "jvandertil"
	linkedin = "jvandertil"

    enableOldContentWarning = true
	oldContentWarningDays = 1090
	backToTopText = "Back to top"

	githubRepoUrl = "https://www.github.com/jvandertil/blog"
	githubMainBranch = "main"

	# Defined in environment configs
	commentHookUrl = ""

[menu]
	[[menu.main]]
		identifier = "posts"
		name = "This is the blog section"
		title = "Posts"
		url = "/posts/"
		weight = -110

	[[menu.main]]
		identifier = "about"
		name = "About"
		title = "About"
		url = "/about/"

	[[menu.footer]]
		identifier = "cookiestatement"
		name = "Cookie statement"
		title = "Cookie statement"
		url = "/cookie-statement/"
