trigger:
  paths:
    include:
      - src/Uploader/*
      - .ci/azure-pipelines/BlogUploaderCI.yml
      - eng/build-uploader.sh

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 5 sdk'
      inputs:
        packageType: sdk
        version: 5.0.x
    - bash: eng/build-uploader.sh
      displayName: 'Run build script'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish uploader'
      inputs:
        targetPath: 'artifacts/uploader'
        artifact: 'bin'
        publishLocation: 'pipeline'
