trigger:
  paths:
    include:
      - eng/deploy/*

jobs:
- job: Package
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish scripts'
      inputs:
        targetPath: 'eng/deploy'
        artifact: 'scripts'
        publishLocation: 'pipeline'
