trigger: none

variables:
  uploaderArtifact: '$(Pipeline.Workspace)/BlogUploaderCI/bin'
  pulumiArtifact: '$(Pipeline.Workspace)/BlogInfraCI/pulumi'
  blogArtifact: '$(Pipeline.Workspace)/BlogContentCI/content'
  deploymentScriptsArtifact: '$(Pipeline.Workspace)/BlogDeployScriptsCI/scripts'
  pulumiStack: tst
  system.debug: true

resources:
  pipelines:
  - pipeline: BlogUploaderCI
    source: Blog.Uploader.CI
    branch: master
    trigger: none
  - pipeline: BlogContentCI
    source: Blog.Content.CI
    branch: master
    trigger:
      branches:
      - master
  - pipeline: BlogInfraCI
    source: Blog.Infra.CI
    branch: feature/deploy-pipeline
    trigger:
      branches:
      - master
  - pipeline: BlogDeployScriptsCI
    source: Blog.DeployScripts.CI
    branch: feature/deploy-pipeline
    trigger:
      branches:
      - master

jobs:
- deployment: AzureDeploy
  pool:
    vmImage: 'windows-latest'
  environment: jvandertil-blog-prd
  strategy: 
    runOnce:
      deploy:
        steps:
          - download: BlogContentCI
            displayName: 'Download blog content artifact'
          - download: BlogUploaderCI
            displayName: 'Download blog uploader artifact'
          - download: BlogInfraCI
            displayName: 'Download blog infrastructure artifact'
          - download: BlogDeployScriptsCI
            displayName: 'Download deployment scripts artifact'

          - task: PowerShell@2
            displayName: Install Pulumi
            inputs:
              targetType: 'inline'
              script: |
                [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
                iex ((New-Object System.Net.WebClient).DownloadString("https://get.pulumi.com/install.ps1"))
                Write-Host "##vso[task.prependpath]$env:USERPROFILE\.pulumi\bin"

          - task: AzureCLI@2
            displayName: 'Run deployment script'
            inputs:
              azureSubscription: 'Azure jvandertil.nl prd'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                $env:ARM_CLIENT_ID = $env:servicePrincipalId
                $env:ARM_CLIENT_SECRET = $env:servicePrincipalKey
                $env:ARM_TENANT_ID = $env:tenantId
                $env:ARM_SUBSCRIPTION_ID = '$(Azure.SubscriptionId)'
                
                $(deploymentScriptsArtifact)/deploy-blog.ps1 -BlogArtifact "$(blogArtifact)" -UploaderArtifact "$(uploaderArtifact)" -PulumiArtifact "$(pulumiArtifact)" -PulumiStack "$(pulumiStack)" -CloudFlareZoneId "$(CloudFlare.ZoneId)" -CloudFlareApiKey "$(CloudFlare.ApiKey)"
              addSpnToEnvironment: true
            env:
              PULUMI_ACCESS_TOKEN: $(Pulumi.AccessToken)
