using System.Text;
using Humanizer;
using Vandertil.Blog.Pipeline.StronglyTypedBicepGenerator.Parser;

if (args.Length < 4)
{
    Console.Error.WriteLine("Usage: BicepPsGenerator --input <bicep-path> --output <psm1-path>");
    return 1;
}

var argsDict = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
for (int i = 0; i < args.Length - 1; i++)
{
    if (args[i].StartsWith("--"))
    {
        argsDict[args[i]] = args[i + 1];
        i++;
    }
}

if (!argsDict.TryGetValue("--input", out string? inputPath))
{
    Console.Error.WriteLine("Missing --input argument.");
    return 1;
}

if (!argsDict.TryGetValue("--output", out string? outputPath))
{
    Console.Error.WriteLine("Missing --output argument.");
    return 1;
}

var bicepFile = BicepParser.ParseFile(inputPath);

var sb = new StringBuilder();
sb.AppendLine($"# Auto-generated by BicepPsGenerator from {Path.GetFileName(inputPath)}. Do not edit manually.");
sb.AppendLine("#Requires -Version 7.0");
sb.AppendLine();

if (bicepFile.Outputs.Count > 0)
{
    AppendGetDeploymentFunction(sb, bicepFile.Name, bicepFile.Outputs);
}

foreach (var module in bicepFile.Modules.OrderBy(x => x.Name))
{
    AppendModuleFunctions(sb, module);
}

if (bicepFile.Parameters.Count > 0)
{
    AppendNewParametersFunction(sb, bicepFile.Name, bicepFile.Parameters);
}

var outputDir = Path.GetDirectoryName(outputPath);
if (!string.IsNullOrEmpty(outputDir))
{
    Directory.CreateDirectory(outputDir);
}

File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
Console.WriteLine($"Generated: {outputPath}");
return 0;

static void AppendGetDeploymentFunction(StringBuilder sb, string deploymentName, IEnumerable<BicepOutput> outputs)
{
    var functionName = $"Get-{ToPascalCase(deploymentName)}Deployment";

    sb.AppendLine($"function {functionName} {{");
    sb.AppendLine("    [CmdletBinding()]");
    sb.AppendLine("    param(");
    sb.AppendLine("        [Parameter(Mandatory)]");
    sb.AppendLine("        [string] $ResourceGroup");
    sb.AppendLine("    )");
    sb.AppendLine();
    sb.AppendLine($"    $outputs = az deployment group show ``");
    sb.AppendLine($"        --resource-group $ResourceGroup ``");
    sb.AppendLine($"        --name {deploymentName} ``");
    sb.AppendLine("        --query properties.outputs ``");
    sb.AppendLine("        --output json | ConvertFrom-Json");
    sb.AppendLine();
    sb.AppendLine("    return [PSCustomObject]@{");
    foreach (var output in outputs.OrderBy(x => x.Name))
    {
        var propName = ToPascalCase(output.Name);
        sb.AppendLine($"        {propName,-44} = $outputs.{output.Name}.value");
    }
    sb.AppendLine("    }");
    sb.AppendLine("}");
    sb.AppendLine();
}

static void AppendModuleFunctions(StringBuilder sb, BicepModule module)
{
    if (module.Outputs.Count > 0)
    {
        AppendGetDeploymentFunction(sb, module.Name, module.Outputs);
    }

    foreach (var nested in module.Modules.OrderBy(x => x.Name))
    {
        AppendModuleFunctions(sb, nested);
    }
}

static void AppendNewParametersFunction(StringBuilder sb, string bicepName, IEnumerable<BicepParameter> parameters)
{
    var functionName = $"New-{ToPascalCase(bicepName)}Parameters";
    var paramList = parameters.ToList();

    sb.AppendLine($"function {functionName} {{");
    sb.AppendLine("    [CmdletBinding()]");
    sb.AppendLine("    param(");

    bool first = true;
    foreach (var param in paramList)
    {
        if (!first)
        {
            sb.AppendLine(",");
        }
        if (param.Required)
        {
            sb.AppendLine("        [Parameter(Mandatory)]");
        }
        sb.Append($"        [string] ${ToPascalCase(param.Name)}");
        first = false;
    }
    sb.AppendLine();
    sb.AppendLine("    )");
    sb.AppendLine();
    sb.AppendLine("    $result = [System.Collections.Generic.List[string]]::new()");
    foreach (var param in paramList)
    {
        var psName = ToPascalCase(param.Name);
        if (param.Required)
        {
            sb.AppendLine($"    $result.Add(\"{param.Name}=$${psName}\")");
        }
        else
        {
            sb.AppendLine($"    if ($PSBoundParameters.ContainsKey('{psName}') -and -not [string]::IsNullOrEmpty(${psName})) {{");
            sb.AppendLine($"        $result.Add(\"{param.Name}=$${psName}\")");
            sb.AppendLine("    }");
        }
    }
    sb.AppendLine("    return $result.ToArray()");
    sb.AppendLine("}");
    sb.AppendLine();
}

static string ToPascalCase(string name)
{
    // Handles camelCase and kebab-case inputs
    return name.Replace('-', '_').Pascalize();
}
