name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          name: build
          path: ./artifacts
    
      - name: Azure CLI Action
        uses: Azure/cli@v2
        with: 
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/build.sh
            $GITHUB_WORKSPACE/build.sh Deploy --environment prd --cloudflare-api-key $CLOUDFLARE_API_KEY --cloudflare-zone-id $CLOUDFLARE_ZONE_ID
        env:
          
      