name: Update Hugo Version

on:
  schedule:
    - cron: "0 3 * * *" # Every day at 03:00 UTC
  workflow_dispatch:

jobs:
  update-hugo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest Hugo version
        id: hugo
        run: |
          latest=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r .tag_name | sed 's/^v//')
          echo "latest=$latest" >> $GITHUB_OUTPUT

      - name: Read current Hugo version from source file
        id: current
        run: |
          current=$(grep -oP 'private const string HugoVersion = "\K[0-9\.]+' path/to/YourFile.cs)
          echo "current=$current" >> $GITHUB_OUTPUT

      - name: Compare versions and update if needed
        id: update
        run: |
          latest="${{ steps.hugo.outputs.latest }}"
          current="${{ steps.current.outputs.current }}"
          if [ "$latest" != "$current" ]; then
            sed -i "s/private const string HugoVersion = \".*\";/private const string HugoVersion = \"$latest\";/" path/to/YourFile.cs
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.update.outputs.updated == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update HugoVersion to ${{ steps.hugo.outputs.latest }}"
          branch: update/hugo-version-${{ steps.hugo.outputs.latest }}
          title: "chore: update HugoVersion to ${{ steps.hugo.outputs.latest }}"
          body: |
            This PR updates the HugoVersion constant to ${{ steps.hugo.outputs.latest }}.
          labels: dependencies